### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by softprops** [julienXX/fingers#1]
Very cool idea. Is this project still maintained? If so are you planning on publishing binaries?

**Comment by julienXX** [comment]
@softprops thanks! Yes it's still somewhat maintained. As for publishing binaries I still need to figure out what's the simplest solution to do cross-compilation on my mac.

**Comment by softprops** [comment]
Would you be open to prs?

**Comment by julienXX** [comment]
Certainly :)
